#!/usr/bin/env bash
# Wine brand-identity policy round. Analysis only; no production/fixture/issue change.
# Branch: research/wine-brand-identity-policy   Base: see git-sha.txt
set -euo pipefail
A=artifacts/wine-brand-identity-policy
git rev-parse HEAD > "$A/git-sha.txt"

# Regulatory sources retrieved via WebFetch from the Cornell LII CFR mirror on
# 2026-07-21 (eCFR was behind a bot wall; TTB guidance pages timed out). See
# source-memo.md for exact URLs, quoted text, and amendment dates.

# Corpus data: 13 primary + 10 control fixtures, from the committed manifest and
# the committed extractor report (no OCR re-run).
node "$A/build-cases.mjs"      # assessments.json + manifest + report -> cases.json

# Matrix + aggregates are generated by the inline node script recorded in the
# session; both read cases.json only.

# Validation
for f in "$A"/*.json; do node -e "JSON.parse(require('fs').readFileSync('$f','utf8'))"; done
bash -n "$A/commands.sh"
git status --porcelain -- src scripts tests docs public   # expected: empty
